apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: glw_crb
subjects:
- kind: User
  name: carol
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: glw_pods
