apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  namespace: elastic-system
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: elasticsearch
  local:
    path: /mnt/disk/vdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker3